# Generated by Django 4.2.1 on 2023-05-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_user'),
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeddata', to='userprofile.profile'),
        ),
    ]
